[package]
name = "ocf"
version = "0.2.0-alpha.4"
authors = ["arcnmx"]
build = "build.rs"

description = "Open Container Specification"
documentation = "http://arcnmx.github.io/ocf-rs/ocf/"
repository = "https://github.com/arcnmx/ocf-rs"
readme = "README.md"
keywords = ["oci", "open", "container", "docker", "runc"]
license = "MIT"

[lib]
path = "src/mod.rs"

[dependencies]
serde = "^0.6.7"
serde_macros = { version = "^0.6.5", optional = true }
serde_json = "^0.6.0"
serde-value = "^0.0.1"
semver = "^0.2.1"

[build-dependencies]
serde_codegen = { version = "^0.6.8", optional = true }
syntex = { version = "^0.25.0", optional = true }

[features]
stable = ["serde_codegen", "syntex"]
unstable = ["serde_macros"]
